title: Shiomountain Docs
description: Shiomountain's documents
theme: just-the-docs

url: https://shiomountain.github.io/shiomountain_doc/

aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
  Twitter Account: https://twitter.com/Shiomountain
